#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

NERON_ROOT="${NERON_ROOT:-/etc/neronOS}"
ENV_FILE="${ENV_FILE:-$NERON_ROOT/secrets.env}"
GATEWAYS_URL="${NERON_GATEWAYS_URL:-http://127.0.1.8:8070}"

for bin in curl jq; do
  if ! command -v "$bin" >/dev/null 2>&1; then
    printf '%s✗ %s introuvable%s : installe-le avant de relancer ce script (ex. apt install %s).\n' \
      "$RED" "$bin" "$RESET" "$bin" >&2
    exit 1
  fi
done

TOTAL_STAGES=5

banner "Connecter Néron à Google Agenda"

# ── Stage 1 : clé d'API du service gateways ────────────────────────────────
stage "Clé d'API du service gateways"
say "gateways refuse toute requête sans clé (fail-closed). On s'assure qu'une"
say "clé existe déjà dans secrets.env avant de continuer."
EXISTING_KEY=$(_existing NERON_GATEWAYS_API_KEY || true)
if [[ -n "$EXISTING_KEY" ]]; then
  note "NERON_GATEWAYS_API_KEY déjà présente dans $ENV_FILE, on la garde."
  GATEWAYS_API_KEY="$EXISTING_KEY"
else
  GATEWAYS_API_KEY=$(openssl rand -hex 32 2>/dev/null || head -c32 /dev/urandom | od -An -tx1 | tr -d ' \n')
  write_env NERON_GATEWAYS_API_KEY "$GATEWAYS_API_KEY"
fi

# ── Stage 2 : projet Google Cloud + API Calendar ───────────────────────────
stage "Projet Google Cloud et API Calendar"
say "Il faut un projet Google Cloud avec l'API Google Calendar activée."
open_url "https://console.cloud.google.com/projectcreate"
step "Crée un projet (ou choisis-en un existant que tu contrôles)."
open_url "https://console.cloud.google.com/apis/library/calendar-json.googleapis.com"
step "Sur cette page (le bon projet sélectionné en haut), clique 'Activer'."
note "Si ce lien direct ne correspond plus à l'UI actuelle, cherche 'Google Calendar API' dans la bibliothèque d'API."
pause "Une fois l'API Calendar activée, appuie sur Entrée."

# ── Stage 3 : écran de consentement OAuth ──────────────────────────────────
stage "Écran de consentement OAuth"
say "Google exige un écran de consentement avant de créer des identifiants."
open_url "https://console.cloud.google.com/apis/credentials/consent"
step "Type 'External' (ou 'Internal' si compte Google Workspace), nom de l'app"
step "  au choix (ex. 'Néron'), email de support = le tien. Enregistre."
step "Ajoute ton propre compte Google comme 'Test user' si l'app reste en mode test."
pause "Une fois l'écran de consentement configuré, appuie sur Entrée."

# ── Stage 4 : identifiant OAuth (device flow) ──────────────────────────────
stage "Identifiant OAuth (TVs and Limited Input devices)"
say "Néron utilise le flux 'device authorization grant' : pas de callback web,"
say "donc un identifiant de type TV/appareil à entrées limitées, pas 'Web application'."
open_url "https://console.cloud.google.com/apis/credentials"
step "Create Credentials → OAuth client ID → Application type = 'TVs and Limited Input devices'"
step "Nom au choix (ex. 'Néron gateways'), puis Create."
step "Une fenêtre affiche le Client ID et le Client Secret : copie-les."
ask NERON_GATEWAY_GOOGLE_CLIENT_ID "Colle le Client ID :"
ask_secret NERON_GATEWAY_GOOGLE_CLIENT_SECRET "Colle le Client Secret :"
write_env NERON_GATEWAY_GOOGLE_CLIENT_ID "$NERON_GATEWAY_GOOGLE_CLIENT_ID"
write_env NERON_GATEWAY_GOOGLE_CLIENT_SECRET "$NERON_GATEWAY_GOOGLE_CLIENT_SECRET"

say "Ces variables ne sont lues qu'au démarrage du service : il faut le relancer."
if confirm "Relancer neron@gateways.service maintenant (sudo systemctl restart) ?"; then
  if sudo systemctl restart neron@gateways.service 2>/dev/null; then
    note "neron@gateways.service relancé."
    sleep 2
  else
    SKIPPED+=("redémarrage de neron@gateways.service (relance-le à la main)")
    warn "le redémarrage a échoué ; relance-le toi-même puis continue."
    pause "Appuie sur Entrée une fois le service relancé."
  fi
else
  SKIPPED+=("redémarrage de neron@gateways.service (relance-le à la main)")
  pause "Relance-le toi-même, puis appuie sur Entrée pour continuer."
fi

# ── Stage 5 : autorisation Google (device flow) ────────────────────────────
stage "Autorisation de ton compte Google"
say "On démarre le flux OAuth : Google va te donner un code à saisir sur"
say "n'importe quel appareil (téléphone, laptop)."

START_RESPONSE=$(curl -sS -X POST \
  -H "X-Gateways-Key: $GATEWAYS_API_KEY" \
  "$GATEWAYS_URL/gateways/google/oauth/start") || {
    warn "impossible d'appeler $GATEWAYS_URL/gateways/google/oauth/start"
    warn "vérifie que neron@gateways.service tourne, puis relance ce script."
    exit 1
  }

if ! printf '%s' "$START_RESPONSE" | jq -e '.user_code' >/dev/null 2>&1; then
  warn "réponse inattendue du service gateways :"
  printf '%s\n' "$START_RESPONSE" >&2
  exit 1
fi

USER_CODE=$(printf '%s' "$START_RESPONSE" | jq -r '.user_code')
VERIFICATION_URL=$(printf '%s' "$START_RESPONSE" | jq -r '.verification_url')
INTERVAL=$(printf '%s' "$START_RESPONSE" | jq -r '.interval')
EXPIRES_IN=$(printf '%s' "$START_RESPONSE" | jq -r '.expires_in')

printf '\n  %s%s  Code à saisir : %s%s\n' "$BOLD" "$GREEN" "$USER_CODE" "$RESET"
say "Va sur $VERIFICATION_URL et saisis ce code (valable $((EXPIRES_IN / 60)) min)."
open_url "$VERIFICATION_URL"
pause "Une fois le code saisi et l'accès approuvé côté Google, appuie sur Entrée."

say "Vérification auprès de Google..."
MAX_ATTEMPTS=$(( (EXPIRES_IN / INTERVAL) + 2 ))
CONNECTED=0
for ((i = 1; i <= MAX_ATTEMPTS; i++)); do
  POLL_RESPONSE=$(curl -sS -X POST \
    -H "X-Gateways-Key: $GATEWAYS_API_KEY" \
    "$GATEWAYS_URL/gateways/google/oauth/poll") || {
      warn "erreur réseau en interrogeant $GATEWAYS_URL, nouvelle tentative..."
      sleep "$INTERVAL"
      continue
    }
  STATUS=$(printf '%s' "$POLL_RESPONSE" | jq -r '.status // "error"')
  if [[ "$STATUS" == "connected" ]]; then
    CONNECTED=1
    break
  elif [[ "$STATUS" == "pending" ]]; then
    note "en attente de validation... (essai $i/$MAX_ATTEMPTS)"
    sleep "$INTERVAL"
  else
    warn "Google a refusé ou une erreur est survenue :"
    printf '%s\n' "$POLL_RESPONSE" >&2
    break
  fi
done

if (( CONNECTED )); then
  printf '  %s✓ Google est connecté.%s\n' "$GREEN" "$RESET"
else
  SKIPPED+=("connexion Google (relance ce script pour réessayer le flux OAuth)")
  warn "la connexion n'a pas abouti dans le temps imparti."
fi
# ──────────────────────────────────────────────────────────────────────────

finish
